### ISSUE TITLE
Ele Shaman Breaks when entering BG.

### ISSUE THREAD

**Issue by jj1232727** [mwojtkowski/Ovale#23]
As soon as I enter a BG and place one spell on a target it asks to spam Earth Shock and nothing else. Reload is only thing that fixes it. As soon as I reload I don't have to do it again until the next BG.

Edit: Happens on all specs. It breaks if you enter any new instance.

Also if you switch specs script does not save settings.

**Comment by mwojtkowski** [comment]
Do you get any lua errors when it does that ?

**Comment by jj1232727** [comment]
Nope. No errors.
Everytime I join a new instance it does the following.
On Priest it will show only Mind Blast
On Ele Shaman Earth Shock
DK Frost Frost Strike

As soon as I reload it fixes it for the whole instance.

**Comment by mwojtkowski** [comment]
I never do BG's so that's why I didn't saw that error and yes you get lots of lua errors ( I'm using BugGrabber/BugSack )

For some reason when you enter BG UnitPowerMax() returns 0 for every power type Holy Power, Maelstrom etc. and there is condition in max power to remove any power with max equal to 0 which is cause of this error
